version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: dockerfile
      args: 
        - IRIS_PASSWORD=$IRIS_PASSWORD
    command: --check-caps false -a /opt/irisapp/script_iris.sh
    hostname: iris
    restart: unless-stopped
    env_file: 
      - .env
    ports: 
      - 32782:1972
      - 32783:52773
      - 32784:53773
    volumes:
      - ./:/irisdev/app