Class Medidoc.CommentaarBlok Extends (%Persistent, %XML.Adaptor)
{

Storage Default
{
<Data name="CommentaarBlokDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Medidoc.CommentaarBlokD</DataLocation>
<DefaultData>CommentaarBlokDefaultData</DefaultData>
<IdLocation>^Medidoc.CommentaarBlokD</IdLocation>
<IndexLocation>^Medidoc.CommentaarBlokI</IndexLocation>
<StreamLocation>^Medidoc.CommentaarBlokS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
